### PR TITLE
Add Apps#find and Apps#all endpoint [Delivers #110588886]

### PR DESCRIPTION
**Pull request by zegomesjf**
@chute/backend

### CODE REVIEW

**Comment by gauravs** [comment]
:+1:

**Comment by evandrodutra** [comment]
:+1:

**Comment by ozeias** [comment]
:+1:

**Comment by ctide** [comment]
:+1:

**Comment by gauravs** [comment]
hi @ctide !!

**Comment by ctide** [comment]
hi @gauravs! :)

**Pull request merged**
